# Generated by Django 4.1.3 on 2022-12-18 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='E-mail')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Имя')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False, verbose_name='Админ')),
                ('level', models.IntegerField(default=0, verbose_name='Уровень')),
                ('exp', models.IntegerField(default=0, verbose_name='Опыт')),
                ('needExpToNextLevel', models.IntegerField(default=10, verbose_name='Опыт до следующего уровня')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
