# Generated by Django 4.1.3 on 2022-12-19 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание упражнения')),
                ('time', models.IntegerField(blank=True, null=True, verbose_name='Время выполнения')),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название тренировки')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание тренировки')),
                ('image', models.ImageField(blank=True, null=True, upload_to='trainings', verbose_name='Изображение')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainings.exercise')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainings.training')),
            ],
        ),
        migrations.AddField(
            model_name='training',
            name='list_of_exercises',
            field=models.ManyToManyField(through='trainings.TrainingExercise', to='trainings.exercise'),
        ),
    ]
