# Generated by Django 4.1.3 on 2022-12-19 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='exp',
            field=models.IntegerField(blank=True, null=True, verbose_name='Опыт'),
        ),
    ]
